CREATE TABLE token
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    access_token  VARCHAR(255),
    refresh_token VARCHAR(255),
    is_logged_out BOOLEAN,
    user_id       UUID,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

ALTER TABLE token
    ADD CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

